plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.12'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.11.4"))
    testImplementation(platform("io.cucumber:cucumber-bom:7.21.1"))

    testImplementation("io.cucumber:cucumber-java")
    testImplementation("io.cucumber:cucumber-junit-platform-engine")
    testImplementation("org.junit.platform:junit-platform-suite")
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
}

javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass = 'ca.mcgill.ecse.fashionstoremanagement.application.FashionStoreApplication'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named("test") {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
    systemProperty("cucumber.junit-platform.naming-strategy", "long")
}

tasks.register('copyResources', Copy) {
    from "src/main/java/ca/mcgill/ecse/fashionstoremanagement"
    into "build/classes/java/main/ca/mcgill/ecse/fashionstoremanagement"
    exclude "**/*.java"
}

tasks.named('run') {
    dependsOn tasks.named('copyResources')
}