package ca.mcgill.ecse.fashionstoremanagement.feature;

import ca.mcgill.ecse.fashionstoremanagement.controller.FashionStoreException;
import ca.mcgill.ecse.fashionstoremanagement.controller.OrderController;
import ca.mcgill.ecse.fashionstoremanagement.controller.OrderProcessingController;
import ca.mcgill.ecse.fashionstoremanagement.model.*;
import io.cucumber.java.Before;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

import java.sql.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.lang.reflect.Field;

import static org.junit.jupiter.api.Assertions.*;

public class OrderStepDefinitions extends StepDefinitions {

    // Maps the fake order id used in the feature files to the real autogenerated order numbers.
    private Map<String, Integer> orderIds;

    // remembers the order created in the When step
    private Order lastCreatedOrder;

    @Before
    public void before() {
        super.before();
        orderIds = new HashMap<>();
        lastCreatedOrder = null;
    }

    @Given("the following orders exist in the system")
    public void theFollowingOrdersExistInTheSystem(List<Map<String, String>> dataTable) throws NoSuchFieldException, IllegalAccessException {
        for (Map<String, String> row : dataTable) {
            String featureId = row.get("id");
            String datePlacedString = row.get("datePlaced");
            String deadlineString = row.get("deadline");
            String customerUsername = row.get("customer");
            String orderState = row.get("state");
            String assigneeUsername = row.get("assignee");

            // Convert "NULL" from the feature file into Java null, otherwise parse the SQL date.
            Date datePlaced;
            if ("NULL".equals(datePlacedString)) {
                datePlaced = null;
            } else {
                datePlaced = Date.valueOf(datePlacedString);
            }

            Employee assignee = null;
            if ("NULL".equals(assigneeUsername)) {
                assignee = null;
            }
            else {
                List<Employee> employees = getSystem().getEmployees();
                for (Employee employee : employees) {
                    if (employee.getUser().getUsername().equals(assigneeUsername)) {
                        assignee = employee;
                        break;
                    }
                }
            }

            // Convert deadline string such as "SameDay" into the enum value used by the model.
            Order.DeliveryDeadline deadline = Order.DeliveryDeadline.valueOf(deadlineString);

            // Find the user, then verify that the user is actually a customer.
            Customer customer = null;
            for (Customer c : getSystem().getCustomers()) {
                if (c.getUser().getUsername().equals(customerUsername)) {
                    customer = c;
                    break;
                }
            }
            assertNotNull(customer, "No customer found with username " + customerUsername);

            // Create the order directly in the model for the Given step.
            Order order = new Order(assigneeUsername, datePlaced, deadline, getSystem(), customer);

//            Field orderStateField = Order.class.getDeclaredField("state");
//            orderStateField.setAccessible(true);
//            orderStateField.set(order, Order.State.valueOf(orderState));

            // Save the mapping from the fake feature file id to the real autogenerated order number.
            orderIds.put(featureId, order.getOrderNumber());
        }
    }

    // TODO: update total cost every time an item is added to the order
    @Given("the following items are part of orders")
    public void theFollowingItemsArePartOfOrders(List<Map<String, String>> dataTable) {
        for (Map<String, String> row : dataTable) {
            String featureOrderId = row.get("order");
            String itemName = row.get("item");
            String sizeString = row.get("size");
            int quantity = Integer.parseInt(row.get("quantity"));

            // Use the fake order id from the feature file to get the actual order in the system.
            Order order = getOrderByFeatureId(featureOrderId);
            assertNotNull(order, "No order found for feature ID " + featureOrderId);

            // Find the item by name.
            Item item = Item.getWithName(itemName);
            assertNotNull(item, "No item found with name " + itemName);

            // Find the sized version of the item, e.g. T-Shirt in size M.
            SizedItem sizedItem = findSizedItem(item, sizeString);
            assertNotNull(sizedItem, "No sized item found for " + itemName + " in size " + sizeString);

            // Add the item directly to the order in the model for the Given step.
            order.addOrderItem(quantity, getSystem(), sizedItem);
        }
    }

    @Given("the order with ID {string} has {int} distinct items")
    public void theOrderWithIDHasDistinctItems(String id, int count) {
        // Write code here that turns the phrase above into concrete actions

        Order order = getOrderByFeatureId(id);
        assertNotNull(order, "No order found for ID" + id);

        FashionStoreManagement system = getSystem();

        int currentCount = order.numberOfOrderItems();
        for(int i = currentCount; i < count; i++){
            Item dummyItem = new Item("dummyItem" + i, 1.0, 0, system);
            SizedItem dummySizedItem = new SizedItem(SizedItem.Size.M, 100, system, dummyItem);
            order.addOrderItem(1, system, dummySizedItem);
        }
    }

    @When("{string} attempts to create an order with deadline {string}")
    public void attemptsToCreateAnOrderWithDeadline(String username, String deadline) {
        try {
            // Convert "NULL" to null because the invalid scenario uses NULL as text.
            String actualDeadline;
            if ("NULL".equals(deadline)) {
                actualDeadline = null;
            } else {
                actualDeadline = deadline;
            }

            // Call the controller and store the newly created order for other  checks.
            lastCreatedOrder = OrderController.createOrder(username, actualDeadline);
            error = null;
        } catch (FashionStoreException e) {
            lastCreatedOrder = null;
            error = e;
        }
    }

    @When("the user attempts to delete the order with ID {string}")
    public void theUserAttemptsToDeleteTheOrderWithID(String id) {
        try {
            // Convert the fake file id  to a real autogenerated order number.
            int realOrderNumber = resolveOrderNumber(id);
            OrderController.deleteOrder(realOrderNumber);
            error = null;
        } catch (FashionStoreException e) {
            error = e;
        }
    }

    @When("the user attempts to delete the non-existent order with ID {string}")
    public void theUserAttemptsToDeleteTheNonExistentOrderWithOrderNumberOrderNumber(String id) {
        try {
            // In this scenario the id is meant to be a raw non existent order number.
            OrderController.deleteOrder(Integer.parseInt(id));
            error = null;
        } catch (FashionStoreException e) {
            error = e;
        }
    }

    @When("the user attempts to add item {string} in size {string} to the order with ID {int}")
    public void theUserAttemptsToAddItemInSizeToTheOrderWithID(String itemName, String size, int id) {
        try {
            // Convert the fake feature file id to the real autogenerated order number.
            int realOrderNumber = resolveOrderNumber(String.valueOf(id));
            OrderController.addItemToOrder(realOrderNumber, itemName, size, 1);
            error = null;
        } catch (FashionStoreException e) {
            error = e;
        }
    }

    @When("the user attempts to add item {string} in size {string} to the non-existent order with order number {int}")
    public void theUserAttemptsToAddItemInSizeToTheNonExistentOrderWithOrderNumberOrderNumber(String itemName, String size, int orderId) {
        try {
            // In this scenario the given id is already a raw nonexistent order number.
            OrderController.addItemToOrder(orderId, itemName, size, 1);
            error = null;
        } catch (FashionStoreException e) {
            error = e;
        }
    }

    @When("the user attempts to set the quantity of item {string} in size {string} in the order with ID {string} to {int}")
    public void theUserAttemptsToSetTheQuantityOfItemInSizeInTheOrderWithIDTo(String itemName, String size, String orderId, int quantity) {
        try {
            // Convert the fake file id to a real autogenerated order number.
            int realOrderNumber = resolveOrderNumber(orderId);
            OrderController.setOrderItemQuantity(realOrderNumber, itemName, size, quantity);
            error = null;
        } catch (FashionStoreException e) {
            error = e;
        }
    }

    @When("the user attempts to set the quantity of item {string} in size {string} in the non-existent order {int} to {int}")
    public void theUserAttemptsToSetTheQuantityOfItemInSizeInTheNonExistentOrderOrderNumberToNewQty(String itemName, String size, int id, int quantity) {
        try {

            OrderController.setOrderItemQuantity(id, itemName, size, quantity);
            error = null;
        } catch (FashionStoreException e) {
            error = e;
        }
    }

    @Then("{string} shall have a new order")
    public void shallHaveANewOrder(String username) {
        // Verify that an order was created and that it belongs to the expected customer.
        assertNotNull(lastCreatedOrder, "No order was created");
        assertEquals(username, lastCreatedOrder.getOrderPlacer().getUser().getUsername());
    }

    @Then("the newly-created order shall have deadline {string}")
    public void theNewlyCreatedOrderShallHaveDeadline(String deadline) {
        // Verify the deadline of the order that was most recently created.
        assertNotNull(lastCreatedOrder, "No order was created");
        assertEquals(Order.DeliveryDeadline.valueOf(deadline), lastCreatedOrder.getDeadline());
    }

    @Then("the newly-created order shall have {int} items")
    public void theNewlyCreatedOrderShallHaveItems(int count) {
        // Verify the number of distinct order items in the newly created order.
        assertNotNull(lastCreatedOrder, "No order was created");
        assertEquals(count, lastCreatedOrder.numberOfOrderItems());
    }

    @Then("the newly-created order shall not have been placed")
    public void theNewlyCreatedOrderShallNotHaveBeenPlaced() {
        // A newly created order should not yet have a placed date.
        assertNotNull(lastCreatedOrder, "No order was created");
        assertNull(lastCreatedOrder.getDatePlaced());
    }

    @Then("the total number of orders shall be {int}")
    public void theTotalNumberOfOrdersShallBe(int expectedCount) {
        // Verify the total number of orders currently in the system.
        assertEquals(expectedCount, getSystem().getOrders().size());
    }

    @Then("no order shall exist with ID {string}")
    public void noOrderShallExistWithID(String id) {
        // Verify that the order with the given feature file id no longer exists.
        int orderNumber = resolveOrderNumber(id);

        for (Order order : getSystem().getOrders()) {
            assertNotEquals(orderNumber, order.getOrderNumber());
        }
    }

    @Then("an order shall exist with ID {string}")
    public void anOrderShallExistWithID(String id) {
        // Verify that the order with the given feature file id still exists.
        int orderNumber = resolveOrderNumber(id);

        boolean found = false;
        for (Order order : getSystem().getOrders()) {
            if (order.getOrderNumber() == orderNumber) {
                found = true;
            }
        }

        assertTrue(found);
    }

    @Then("the order with ID {string} shall include {int} {string} in size {string}")
    public void theOrderWithIDShallIncludeInSize(String id, int quantity, String name, String size) {
        // Verify that the order contains the specified item and size with the expected quantity.
        Order order = getOrderByFeatureId(id);
        assertNotNull(order, "No order found for ID " + id);

        OrderItem matchingOrderItem = findOrderItem(order, name, size);
        assertNotNull(matchingOrderItem, "Order does not include item " + name + " in size " + size);
        assertEquals(quantity, matchingOrderItem.getQuantity());
    }

    @Then("the order with ID {string} shall include {int} distinct items")
    public void theOrderWithIDShallIncludeNumItemsDistinctItems(String id, int quantity) {
        // Verify the number of distinct order items in the specified order.
        Order order = getOrderByFeatureId(id);
        assertNotNull(order, "No order found for ID " + id);
        assertEquals(quantity, order.numberOfOrderItems());
    }

    @Then("the order with ID {string} shall not include any items called {string}")
    public void theOrderWithIDShallNotIncludeAnyItemsCalled(String id, String itemName) {
        // Verify that none of the order items in the order has the specified item name.
        Order order = getOrderByFeatureId(id);
        assertNotNull(order, "No order found for ID " + id);

        for (OrderItem orderItem : order.getOrderItems()) {
            String currentName = orderItem.getItem().getItem().getName();
            assertNotEquals(itemName, currentName);
        }
    }

    @Then("the order with ID {string} shall include {int} distinct item")
    public void theOrderWithIDShallIncludeDistinctItem(String id, int count) {
        // Same check as the plural version, but for the singular step wording.
        Order order = getOrderByFeatureId(id);
        assertNotNull(order, "No order found for ID " + id);
        assertEquals(count, order.numberOfOrderItems());
    }

    // Helper method to convert either a fake feature file id or a raw order number into a real order number.
    private int resolveOrderNumber(String featureIdOrRealId) {
        if (orderIds.containsKey(featureIdOrRealId)) {
            return orderIds.get(featureIdOrRealId);
        }
        return Integer.parseInt(featureIdOrRealId);
    }

    // Helper method to retrieve an order using the fake id from the feature file.
    private Order getOrderByFeatureId(String featureId) {
        int orderNumber = resolveOrderNumber(featureId);

        for (Order order : getSystem().getOrders()) {
            if (order.getOrderNumber() == orderNumber) {
                return order;
            }
        }

        return null;
    }

    // Helper method to find the SizedItem for an item in the requested size.
    private SizedItem findSizedItem(Item item, String sizeString) {
        for (SizedItem sizedItem : item.getSizedItems()) {
            if (sizedItem.getSize().toString().equals(sizeString)) {
                return sizedItem;
            }
        }
        return null;
    }

    // Helper method to find a matching order item by item name and size inside a specific order.
    private OrderItem findOrderItem(Order order, String itemName, String sizeString) {
        for (OrderItem orderItem : order.getOrderItems()) {
            SizedItem sizedItem = orderItem.getItem();
            String currentItemName = sizedItem.getItem().getName();
            String currentSize = sizedItem.getSize().toString();

            if (currentItemName.equals(itemName) && currentSize.equals(sizeString)) {
                return orderItem;
            }
        }
        return null;
    }
}