package ca.mcgill.ecse.fashionstoremanagement.feature;

import ca.mcgill.ecse.fashionstoremanagement.controller.FashionStoreException;
import ca.mcgill.ecse.fashionstoremanagement.controller.OrderController;
import ca.mcgill.ecse.fashionstoremanagement.controller.OrderProcessingController;
import ca.mcgill.ecse.fashionstoremanagement.model.*;
import io.cucumber.java.Before;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

import java.sql.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

public class OrderStepDefinitions extends StepDefinitions {

    /** * Maps the fake, human-readable order IDs used in the feature files
     * to the real, autogenerated integer order numbers from the system.
     */
    public static Map<String, String> orderIds;

    /** Remembers the order most recently created during a "When" step for later verification. */
    public static Order lastCreatedOrder;

    /**
     * Executes before each scenario to reset the internal state and trackers.
     */
    @Before
    public void before() {
        super.before();
        orderIds = new HashMap<>();
        lastCreatedOrder = null;
    }

    /**
     * Populates the system with an initial set of orders based on a Gherkin data table.
     * @param dataTable the list of maps containing order attributes (id, datePlaced, deadline, customer, state, assignee)
     */
    @Given("the following orders exist in the system")
    public void theFollowingOrdersExistInTheSystem(List<Map<String, String>> dataTable) throws NoSuchFieldException, IllegalAccessException {
        for (Map<String, String> row : dataTable) {
            String featureId = row.get("id");
            String datePlacedString = row.get("datePlaced");
            String deadlineString = row.get("deadline");
            String customerUsername = row.get("customer");
            String orderState = row.get("state");
            String assigneeUsername = row.get("assignee");

            // Convert explicit date strings from the feature file into Java SQL Dates
            Date datePlaced;
            if ("NULL".equals(datePlacedString)) {
                datePlaced = null;
            } else if ("three days ago".equals(datePlacedString)) {
                datePlaced = new Date(System.currentTimeMillis() - (86400000 * 3));
            } else if ("two days ago".equals(datePlacedString)) {
                datePlaced = new Date(System.currentTimeMillis() - (86400000 * 2));
            } else if ("yesterday".equals(datePlacedString)) {
                datePlaced = new Date(System.currentTimeMillis() - 86400000);
            } else if ("today".equals(datePlacedString)) {
                datePlaced = new Date(System.currentTimeMillis());
            } else {
                datePlaced = Date.valueOf(datePlacedString);
            }

            // Resolve the assignee username to an actual Employee object if applicable
            Employee assignee = null;
            if ("NULL".equals(assigneeUsername)) {
                assignee = null;
            } else {
                List<Employee> employees = getSystem().getEmployees();
                for (Employee employee : employees) {
                    if (employee.getUser().getUsername().equals(assigneeUsername)) {
                        assignee = employee;
                        break;
                    }
                }
            }

            // Convert deadline string (e.g., "SameDay") into the corresponding Enum value
            Order.DeliveryDeadline deadline = Order.DeliveryDeadline.valueOf(deadlineString);

            // Verify the requested customer exists in the system
            Customer customer = null;
            for (Customer c : getSystem().getCustomers()) {
                if (c.getUser().getUsername().equals(customerUsername)) {
                    customer = c;
                    break;
                }
            }
            assertNotNull(customer, "No customer found with username " + customerUsername);

            // Create the order directly in the model bypassing the controller for initial setup
            Order order = new Order(assigneeUsername, datePlaced, deadline, getSystem(), customer);
            lastCreatedOrder = order;

            // Force the specific state transitions required by the feature file setup
            if (orderState.equals("pending")) {
                order.setOrderState(Order.State.Pending);
            } else if (orderState.equals("placed")) {
                order.setOrderState(Order.State.Placed);
                order.setDatePlaced(datePlaced);
            } else if (orderState.equals("in preparation")) {
                order.setOrderState(Order.State.InPreparation);
                if (assignee != null) {
                    order.setOrderAssignee(assignee);
                } else {
                    order.setPendingAssigneeUsername("NULL");
                }
                order.setDatePlaced(datePlaced);
            } else if (orderState.equals("ready for delivery")) {
                order.setOrderState(Order.State.ReadyForDelivery);
                order.setOrderAssignee(assignee);
                order.setDatePlaced(datePlaced);
            } else if (orderState.equals("delivered")) {
                order.setOrderState(Order.State.Delivered);
                order.setOrderAssignee(assignee);
                order.setDatePlaced(datePlaced);
            } else if (orderState.equals("cancelled")) {
                order.setOrderState(Order.State.Cancelled);
                order.setOrderAssignee(assignee);
            }

            // Save the mapping from the fake feature file string ID to the real autogenerated integer ID
            orderIds.put(featureId, String.valueOf(order.getOrderNumber()));
            System.out.println(order.toString() + "\nState: " + order.getState() + "\nID: " + order.getOrderNumber());
        }
    }

    /**
     * Populates existing orders with specific items and quantities.
     * @param dataTable the list of maps containing order item associations (order, item, size, quantity)
     */
    @Given("the following items are part of orders")
    public void theFollowingItemsArePartOfOrders(List<Map<String, String>> dataTable) {
        for (Map<String, String> row : dataTable) {
            String featureOrderId = row.get("order");
            String itemName = row.get("item");
            String sizeString = row.get("size");
            int quantity = Integer.parseInt(row.get("quantity"));

            System.out.println("This is the featureOrderID given: " + featureOrderId);

            // Resolve fake ID to actual Order object
            Order order = getOrderByFeatureId(featureOrderId);
            assertNotNull(order, "No order found for feature ID " + featureOrderId);

            // Find the generic parent item by name
            Item item = Item.getWithName(itemName);
            assertNotNull(item, "No item found with name " + itemName);

            // Find the specific sized variant of the item (e.g., T-Shirt in size M)
            SizedItem sizedItem = findSizedItem(item, sizeString);
            assertNotNull(sizedItem, "No sized item found for " + itemName + " in size " + sizeString);

            // Add the item directly to the order in the model
            order.addOrderItem(quantity, getSystem(), sizedItem);
        }
    }

    /**
     * Fills an existing order with a specific number of distinct dummy items for testing limits.
     * @param id the fake string ID of the order
     * @param count the target number of distinct items the order should contain
     */
    @Given("the order with ID {string} has {int} distinct items")
    public void theOrderWithIDHasDistinctItems(String id, int count) {
        Order order = getOrderByFeatureId(id);
        assertNotNull(order, "No order found for ID" + id);

        FashionStoreManagement system = getSystem();
        int currentCount = order.numberOfOrderItems();

        // Dynamically generate dummy items until the target count is reached
        for(int i = currentCount; i < count; i++){
            Item dummyItem = new Item("dummyItem" + i, 1.0, 0, system);
            SizedItem dummySizedItem = new SizedItem(SizedItem.Size.M, 100, system, dummyItem);
            order.addOrderItem(1, system, dummySizedItem);
        }
    }

    /**
     * Attempts to create a brand new order for a specific user.
     * @param username the customer creating the order
     * @param deadline the requested delivery deadline
     */
    @When("{string} attempts to create an order with deadline {string}")
    public void attemptsToCreateAnOrderWithDeadline(String username, String deadline) {
        try {
            // Convert the string literal "NULL" to actual Java null to trigger invalid scenarios
            String actualDeadline = "NULL".equals(deadline) ? null : deadline;

            // Delegate to controller, track the created order, and clear any prior errors
            lastCreatedOrder = OrderController.createOrder(username, actualDeadline);
            error = null;
        } catch (FashionStoreException e) {
            // Capture domain errors for subsequent assertions
            lastCreatedOrder = null;
            error = e;
        }
    }

    /**
     * Attempts to delete a specific order using its mapped string ID.
     * @param id the string identifier mapped to the real order
     */
    @When("the user attempts to delete the order with ID {string}")
    public void theUserAttemptsToDeleteTheOrderWithID(String id) {
        try {
            int realOrderNumber = resolveOrderNumber(id);
            OrderController.deleteOrder(realOrderNumber);
            error = null;
        } catch (FashionStoreException e) {
            error = e;
        }
    }

    /**
     * Attempts to delete a non-existent order to test error handling.
     * @param id the raw integer order number expected to be invalid
     */
    @When("the user attempts to delete the non-existent order with ID {string}")
    public void theUserAttemptsToDeleteTheNonExistentOrderWithOrderNumberOrderNumber(String id) {
        try {
            // Pass the raw ID directly, as it shouldn't exist in the system maps
            OrderController.deleteOrder(Integer.parseInt(id));
            error = null;
        } catch (FashionStoreException e) {
            error = e;
        }
    }

    /**
     * Attempts to add a specified sized item to an order.
     * @param itemName the name of the item
     * @param size the size of the item
     * @param id the mapped string ID of the target order
     */
    @When("the user attempts to add item {string} in size {string} to the order with ID {int}")
    public void theUserAttemptsToAddItemInSizeToTheOrderWithID(String itemName, String size, int id) {
        try {
            int realOrderNumber = resolveOrderNumber(String.valueOf(id));
            // Default quantity is set to 1
            OrderController.addItemToOrder(realOrderNumber, itemName, size, 1);
            error = null;
        } catch (FashionStoreException e) {
            error = e;
        }
    }

    /**
     * Attempts to add an item to a non-existent order to test error handling.
     * @param itemName the name of the item
     * @param size the size of the item
     * @param orderId the raw, non-existent order ID
     */
    @When("the user attempts to add item {string} in size {string} to the non-existent order with order number {int}")
    public void theUserAttemptsToAddItemInSizeToTheNonExistentOrderWithOrderNumberOrderNumber(String itemName, String size, int orderId) {
        try {
            OrderController.addItemToOrder(orderId, itemName, size, 1);
            error = null;
        } catch (FashionStoreException e) {
            error = e;
        }
    }

    /**
     * Attempts to update the quantity of a specific item already in an order.
     * @param itemName the name of the item
     * @param size the size variant of the item
     * @param orderId the string identifier mapped to the real order
     * @param quantity the new desired quantity
     */
    @When("the user attempts to set the quantity of item {string} in size {string} in the order with ID {string} to {int}")
    public void theUserAttemptsToSetTheQuantityOfItemInSizeInTheOrderWithIDTo(String itemName, String size, String orderId, int quantity) {
        try {
            int realOrderNumber = resolveOrderNumber(orderId);
            OrderController.setOrderItemQuantity(realOrderNumber, itemName, size, quantity);
            error = null;
        } catch (FashionStoreException e) {
            error = e;
        }
    }

    /**
     * Attempts to update the quantity of an item in a non-existent order.
     * @param itemName the name of the item
     * @param size the size variant of the item
     * @param id the raw, non-existent order ID
     * @param quantity the new desired quantity
     */
    @When("the user attempts to set the quantity of item {string} in size {string} in the non-existent order {int} to {int}")
    public void theUserAttemptsToSetTheQuantityOfItemInSizeInTheNonExistentOrderOrderNumberToNewQty(String itemName, String size, int id, int quantity) {
        try {
            OrderController.setOrderItemQuantity(id, itemName, size, quantity);
            error = null;
        } catch (FashionStoreException e) {
            error = e;
        }
    }

    /**
     * Verifies that an order was successfully created and assigned to the correct user.
     * @param username the expected username of the order placer
     */
    @Then("{string} shall have a new order")
    public void shallHaveANewOrder(String username) {
        assertNotNull(lastCreatedOrder, "No order was created");
        assertEquals(username, lastCreatedOrder.getOrderPlacer().getUser().getUsername());
    }

    /**
     * Verifies the deadline of the most recently created order.
     * @param deadline the expected deadline Enum as a string
     */
    @Then("the newly-created order shall have deadline {string}")
    public void theNewlyCreatedOrderShallHaveDeadline(String deadline) {
        assertNotNull(lastCreatedOrder, "No order was created");
        assertEquals(Order.DeliveryDeadline.valueOf(deadline), lastCreatedOrder.getDeadline());
    }

    /**
     * Verifies the number of distinct items in the most recently created order.
     * @param count the expected number of items
     */
    @Then("the newly-created order shall have {int} items")
    public void theNewlyCreatedOrderShallHaveItems(int count) {
        assertNotNull(lastCreatedOrder, "No order was created");
        assertEquals(count, lastCreatedOrder.numberOfOrderItems());
    }

    /**
     * Verifies that a newly created order correctly lacks a placement date.
     */
    @Then("the newly-created order shall not have been placed")
    public void theNewlyCreatedOrderShallNotHaveBeenPlaced() {
        assertNotNull(lastCreatedOrder, "No order was created");
        assertNull(lastCreatedOrder.getDatePlaced());
    }

    /**
     * Verifies the absolute total count of orders inside the system.
     * @param expectedCount the expected total count
     */
    @Then("the total number of orders shall be {int}")
    public void theTotalNumberOfOrdersShallBe(int expectedCount) {
        assertEquals(expectedCount, getSystem().getOrders().size());
    }

    /**
     * Verifies that an order mapped to the provided string ID no longer exists in the system.
     * @param id the string identifier of the order to check
     */
    @Then("no order shall exist with ID {string}")
    public void noOrderShallExistWithID(String id) {
        int orderNumber = resolveOrderNumber(id);

        // Iterate through all orders ensuring none match the deleted order's ID
        for (Order order : getSystem().getOrders()) {
            assertNotEquals(orderNumber, order.getOrderNumber());
        }
    }

    /**
     * Verifies that an order mapped to the provided string ID does indeed exist.
     * @param id the string identifier of the order to check
     */
    @Then("an order shall exist with ID {string}")
    public void anOrderShallExistWithID(String id) {
        int orderNumber = resolveOrderNumber(id);

        boolean found = false;
        for (Order order : getSystem().getOrders()) {
            if (order.getOrderNumber() == orderNumber) {
                found = true;
            }
        }
        assertTrue(found);
    }

    /**
     * Verifies that a specific order contains a specific quantity of a specific sized item.
     * @param id the string identifier of the order
     * @param quantity the expected quantity
     * @param name the name of the item
     * @param size the size variant of the item
     */
    @Then("the order with ID {string} shall include {int} {string} in size {string}")
    public void theOrderWithIDShallIncludeInSize(String id, int quantity, String name, String size) {
        Order order = getOrderByFeatureId(id);
        assertNotNull(order, "No order found for ID " + id);

        // Search for the specific matching combination within the order
        OrderItem matchingOrderItem = findOrderItem(order, name, size);
        assertNotNull(matchingOrderItem, "Order does not include item " + name + " in size " + size);
        assertEquals(quantity, matchingOrderItem.getQuantity());
    }

    /**
     * Verifies the count of distinct order items within a specific order.
     * @param id the string identifier of the order
     * @param quantity the expected number of distinct items
     */
    @Then("the order with ID {string} shall include {int} distinct items")
    public void theOrderWithIDShallIncludeNumItemsDistinctItems(String id, int quantity) {
        Order order = getOrderByFeatureId(id);
        assertNotNull(order, "No order found for ID " + id);
        assertEquals(quantity, order.numberOfOrderItems());
    }

    /**
     * Verifies that an order strictly does NOT contain any item matching the provided name.
     * @param id the string identifier of the order
     * @param itemName the name of the item that should be absent
     */
    @Then("the order with ID {string} shall not include any items called {string}")
    public void theOrderWithIDShallNotIncludeAnyItemsCalled(String id, String itemName) {
        Order order = getOrderByFeatureId(id);
        assertNotNull(order, "No order found for ID " + id);

        // Iterate through items to ensure the unwanted item isn't present
        for (OrderItem orderItem : order.getOrderItems()) {
            String currentName = orderItem.getItem().getItem().getName();
            assertNotEquals(itemName, currentName);
        }
    }

    /**
     * Identical verification to the plural variant, accommodated for singular Gherkin phrasing.
     * @param id the string identifier of the order
     * @param count the expected number of distinct items
     */
    @Then("the order with ID {string} shall include {int} distinct item")
    public void theOrderWithIDShallIncludeDistinctItem(String id, int count) {
        Order order = getOrderByFeatureId(id);
        assertNotNull(order, "No order found for ID " + id);
        assertEquals(count, order.numberOfOrderItems());
    }

    // =========================================================================
    // Private Helper Methods
    // =========================================================================

    /**
     * Safely converts either a fake Gherkin string ID or a raw integer ID string into a real order number.
     * @param featureIdOrRealId the string to resolve
     * @return the resolved integer ID
     */
    private int resolveOrderNumber(String featureIdOrRealId) {
        System.out.println("Entering resolveOrderNumber");
        if (orderIds.containsKey(featureIdOrRealId)) {
            System.out.println("The OrderIDs HashMap (HashMap<String, String>) contains the featureOrderID");
            System.out.println("The acquired real order ID is " + orderIds.get(featureIdOrRealId));
            return Integer.parseInt(orderIds.get(featureIdOrRealId));
        }
        System.out.println("The OrderIDs HashMap (HashMap<String, String>) doesn't contain the featureOrderID");
        return Integer.parseInt(featureIdOrRealId);
    }

    /**
     * Retrieves an order object from the system using the mapped Gherkin feature ID.
     * @param featureId the mapped string ID from the Gherkin file
     * @return the matching Order object, or null if not found
     */
    private Order getOrderByFeatureId(String featureId) {
        System.out.println("Entering getOrderBeFeatureId");
        int orderNumber = resolveOrderNumber(featureId);

        for (Order order : getSystem().getOrders()) {
            if (order.getOrderNumber() == orderNumber) {
                return order;
            }
        }
        return null;
    }

    /**
     * Searches a parent item to find the specific variant matching the provided size string.
     * @param item the parent generic item
     * @param sizeString the target size Enum as a string
     * @return the matched SizedItem variant, or null if not found
     */
    private SizedItem findSizedItem(Item item, String sizeString) {
        for (SizedItem sizedItem : item.getSizedItems()) {
            if (sizedItem.getSize().toString().equals(sizeString)) {
                return sizedItem;
            }
        }
        return null;
    }

    /**
     * Searches an order to find an existing order item matching the target name and size.
     * @param order the target order to search
     * @param itemName the target parent item name
     * @param sizeString the target size variant
     * @return the matching OrderItem, or null if not present in the order
     */
    private OrderItem findOrderItem(Order order, String itemName, String sizeString) {
        for (OrderItem orderItem : order.getOrderItems()) {
            SizedItem sizedItem = orderItem.getItem();
            String currentItemName = sizedItem.getItem().getName();
            String currentSize = sizedItem.getSize().toString();

            if (currentItemName.equals(itemName) && currentSize.equals(sizeString)) {
                return orderItem;
            }
        }
        return null;
    }
}